### PR TITLE
Add Mandrel candidate

### PR DESCRIPTION
**Pull request by helpermethod**
Relates to sdkman/sdkman-db-migrations#324.

### CODE REVIEW

**Review by eddumelendez — APPROVED** [review]
LGTM

**Comment by marc0der** [comment]
Looks good, but could do with some test coverage in [this test](https://github.com/sdkman/sdkman-candidates/blob/master/features/java_version_list_by_vendor.feature).

**Comment by helpermethod** [comment]
@marc0der I will start the next ticket with a test, I promise 😄 . Test Last just doesn't work.

**Comment by helpermethod** [comment]
@marc0der Added a basic test.

**Review by marc0der — APPROVED** [review]
LGTM!

**Pull request merged**
