### PR TITLE
The list view should only return visible candidates

### LINKED ISSUE #20: The list view should only return visible candidates
Related to sdkman/sdkman-db-migrations#170.

In order to not overwhelm the user with outdated candidate versions, only those should be shown in the list view that are `visible` (i.e. the `visible` field is set to `true` **or** the `visible` field doesn't exist at all).

### PR DESCRIPTION
**Pull request by helpermethod**
Fixes #20.

### CODE REVIEW

**Comment by helpermethod** [comment]
I'll add a few more tests and squash the commits.

**Review by marc0der — COMMENTED** [review]
It's not a big thing, but shall we use the new finder method explicitly for getting visible versions? It will make the code clearer to understand.

**Comment by helpermethod** [comment]
> It's not a big thing, but shall we use the new finder method explicitly for getting visible versions? It will make the code clearer to understand.

Yes that makes sense.

**Comment by helpermethod** [comment]
Switched to the new finder method, improved the Cucumber spec and squashed all commits.

**Review by marc0der — APPROVED** [review]

**Comment by marc0der** [comment]
This is awesome, thank you!

**Pull request merged**
