### PR TITLE
Sort JDKs correctly

### PR DESCRIPTION
**Pull request by mvitz**
Relates to #24

### CODE REVIEW

**Comment by mvitz** [comment]
@eddumelendez, @helpermethod, and @marc0der can I do/assist in anything to get this merged? Has been a while since I opened this and did not receive any feedback.

**Comment by marc0der** [comment]
Hi @mvitz, apologies for not getting back to you on this one!

I'll move this list functionality from the candidate service into the new native client. The candidate service will be retired and replaced with a new JSON REST [state service](https://github.com/sdkman/sdkman-state). We'll then do all the rendering from the new Rust CLI based on the JSON responses we get from the state service.

In the interim, we can merge this, but it will be replaced pretty soon after the new state API goes live.

**Comment by mvitz** [comment]
Thanks, wasn't aware of this moving and all the available repositories made it even difficult finding this ;-)

Thanks for merging.

**Comment by marc0der** [comment]
Great stuff, and thanks for your effort!
I currently have an issue with our deployment pipeline, but I hope to get this deployed over the weekend.

**Comment by marc0der** [comment]
@mvitz I'll be rolling out the necessary infrastructure changes on Sunday to allow us to deploy your changes. Thanks for waiting so patiently :bow:

**Comment by marc0der** [comment]
@mvitz your changes have now gone live! Can you please give it an :eye: to confirm it's working as you'd expect?

**Comment by mvitz** [comment]
Everything seams to be correct right now. But the case that was mentioned in the issue is no longer present :-)

**Pull request merged**
